#!/usr/bin/env bash
set -eo pipefail

sudo dnf install -y \
    golang \
    zsh \
    neovim \
    direnv \
    jq \
    yq \
    shellcheck \
    shfmt \
    ripgrep \
    fd-find \
    bat \
    tig \
    pinentry \
    podman \
    podman-docker \
    libtree-sitter

git clone https://github.com/jeffreytse/zsh-vi-mode.git ~/.local/zsh-vi-mode

(
  set -x; cd "$(mktemp -d)" &&
  OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
  KREW="krew-${OS}_${ARCH}" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
  tar zxvf "${KREW}.tar.gz" &&
  KREW_ROOT=$HOME/.local/krew ./"${KREW}" install krew
)

# fix permissions
chmod 700 ~/.local/share/gnupg
