#!/usr/bin/env bash
set -eo pipefail

echo "running post-install steps for Arch Linux"

if ! command -v yay >/dev/null; then
    echo "installing AUR helper"
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    (
        cd /tmp/yay
        makepkg -si
    )
fi

echo "installing packages"
sudo pacman -S --needed \
    base-devel \
    man \
    neovim \
    direnv \
    wezterm \
    zsh \
    zsh-completions \
    ttf-sourcecodepro-nerd \
    tree-sitter \
    go \
    jq \
    go-yq \
    ripgrep \
    fd \
    bat \
    gopass \
    xh \
    shellcheck \
    shfmt \
    kubectl \
    krew \
    helm \
    minio-client \
    docker \
    pinentry \
    git-delta \
    tig \
    deno

yay -S --needed \
    zsh-vi-mode \
    ksd

# needs to exist to write history file there
mkdir -p ~/.local/share/tig

echo "finished post-install steps for Arch Linux"
